### PR TITLE
don't reset selectionStart on repeat visit to start container, add test

### LINKED ISSUE #3: getRange incorrectly shifts start position for node-based offsets
### Describe the Bug

First off, I appreciate this little util - it's been helpful for some managing contentEditable selection programmatically. I've stumbled across an interesting little edge case that only seems to affect FF. Check out [this codesandbox](https://codesandbox.io/p/sandbox/epic-thunder-86m3k) for the repro.

Consider the following structure:
```
<div>
     <span>A</span>
     <span>B</span>
     <span>C</span>
</div>
```

The issue stems from when the browser reports the current selection range `startContainer` as the wrapping div, which FF sometimes does (it seems to depend on contentEditable status, maybe other things, but is reproduce-able). Double clicking in the code sandbox to select all results in this behavior (whereas in Chrome, it uses the inner spans as start/end container)

If we call `getRange` with the `div`, our DOM iteration will start at the first child (span A). The traversal then looks like:
- span A (open)
- textNode A
- span A (close)
- span B (open)
- textNode B
- span B (close
- span C (open)
- textNode C
- span C (close)

The problem is that when the iterator is on `span A (close)`, it will report `isBeforeStart()` as TRUE, because the parent node (div) is indeed the `startContainer` & the child index is indeed 0. This incorrectly shifts the `selectionStart` forward by the length of whatever content is in span A (in this case, 1 character).

After trying to grok everything, I think the fix is to only do this `selectionStart` shifting when the current iterator node is on an opening tag. Its guaranteed that every ending tag will have a corresponding opening tag, and we don't want to shift after having already processed text in the selection.

I'm currently using a patch that does this for my own purposes, but wanted to flag this on the original repository. I've put up a fix & test in a commit on a fork [here](https://github.com/billylittlefield/selection-ranges/commit/0847e46802d49827f1a58ef57fdf31c663656f3f) if its helpful (I wasn't able to push a branch to this repo to create a PR). I couldn't get tests running successfully (I imagine the unpinned packages all have many new versions that break things, so without a `package.lock` I can't do a clean install).

### Steps to Reproduce

In Firefox, go to [this codesandbox](https://codesandbox.io/p/sandbox/epic-thunder-86m3k)
Double click the text in the box

### Expected Behavior

EXPECT: The reported selection range to be [0, 6]
ACTUAL: The reported selection range is [1, 6]

### Environment

- Browser: FF 123.0
- OS: Mac Sonoma 14.2.1

### PR DESCRIPTION
**Pull request by billylittlefield**
Ah, figured out how to make a PR from a fork. Here's the proposed fix, although I was not able to get the test suite running locally due to dependency issues.

### Which issue does this PR address?

Closes #3

### CODE REVIEW

**Comment by nikku** [comment]
`v4.0.0` should hopefully allow you to run the test suite locally (again).

You can test against (local) firefox also by executing `npm run dev` and pointing your firefox to `http://localhost:9876/debug.html`.

If you rebase your PR on the latest `main` then we can see if the issue is fixed (also via CI).

**Comment by nikku** [comment]
Update: I rebased myself. Let's see what CI says.

**Comment by nikku** [comment]
Passes tests for both browsers, good job!

**Comment by billylittlefield** [comment]
Awesome, thanks @nikku ! Appreciate it.

**Pull request merged**
